# PyTorch Fundamentals (Rebuilt)

Clean walkthrough with comments, headers, and subheaders for your listed topics.

In [2]:
import torch
import numpy as np
print('torch:', torch.__version__)
print('numpy:', np.__version__)

torch: 2.10.0
numpy: 2.3.2


## 13. Introduction to tensors

In [3]:
scalar = torch.tensor(7)
vector = torch.tensor([1, 2, 3])
matrix = torch.tensor([[1, 2], [3, 4]])
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(scalar, scalar.ndim, scalar.shape)
print(vector, vector.ndim, vector.shape)
print(matrix, matrix.ndim, matrix.shape)
print(tensor3d.ndim, tensor3d.shape)

tensor(7) 0 torch.Size([])
tensor([1, 2, 3]) 1 torch.Size([3])
tensor([[1, 2],
        [3, 4]]) 2 torch.Size([2, 2])
3 torch.Size([2, 2, 2])


## 14. Creating tensors

In [4]:
zeros = torch.zeros((2, 3))
ones = torch.ones((2, 3))
ar = torch.arange(0, 10, 2)
lin = torch.linspace(0, 1, 5)
rand = torch.rand((2, 3))
randi = torch.randint(0, 10, (2, 3))
print(zeros)
print(ones)
print(ar)
print(lin)
print(rand)
print(randi)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([0, 2, 4, 6, 8])
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
tensor([[0.1654, 0.1851, 0.7770],
        [0.9154, 0.7491, 0.7944]])
tensor([[9, 3, 8],
        [2, 5, 7]])


## 17. Tensor datatypes

In [5]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
c = b.to(torch.float64)
print(a.dtype, b.dtype, c.dtype)

torch.int64 torch.float32 torch.float64


## 18. Tensor attributes

In [6]:
t = torch.rand((3, 4), dtype=torch.float32)
print('shape:', t.shape)
print('ndim:', t.ndim)
print('dtype:', t.dtype)
print('device:', t.device)
print('numel:', t.numel())

shape: torch.Size([3, 4])
ndim: 2
dtype: torch.float32
device: cpu
numel: 12


## 19. Manipulating tensors

In [7]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([10, 20, 30])
print('add:', x + y)
print('sub:', y - x)
print('mul elementwise:', x * y)
print('div:', y / x)

add: tensor([11, 22, 33])
sub: tensor([ 9, 18, 27])
mul elementwise: tensor([10, 40, 90])
div: tensor([10., 10., 10.])


## 20. Matrix multiplication

In [8]:
m1 = torch.tensor([[1., 2., 3.], [4., 5., 6.]])
m2 = torch.tensor([[7., 8.], [9., 10.], [11., 12.]])
print('m1 shape:', m1.shape)
print('m2 shape:', m2.shape)
print('matmul:', m1 @ m2)

m1 shape: torch.Size([2, 3])
m2 shape: torch.Size([3, 2])
matmul: tensor([[ 58.,  64.],
        [139., 154.]])


## 23. Finding min, max, mean, sum

In [9]:
v = torch.tensor([2.0, 5.0, 1.0, 9.0, 3.0])
print('min:', v.min())
print('max:', v.max())
print('mean:', v.mean())
print('sum:', v.sum())
print('argmin:', v.argmin())
print('argmax:', v.argmax())

min: tensor(1.)
max: tensor(9.)
mean: tensor(4.)
sum: tensor(20.)
argmin: tensor(2)
argmax: tensor(3)


## 25. Reshaping, viewing and stacking

In [10]:
base = torch.arange(1, 13)
reshaped = base.reshape(3, 4)
viewed = base.view(2, 6)
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print('base:', base)
print('reshape 3x4:', reshaped)
print('view 2x6:', viewed)
print('stack dim0:', torch.stack([a, b], dim=0))
print('stack dim1:', torch.stack([a, b], dim=1))

base: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
reshape 3x4: tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
view 2x6: tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])
stack dim0: tensor([[1, 2, 3],
        [4, 5, 6]])
stack dim1: tensor([[1, 4],
        [2, 5],
        [3, 6]])


## 26. Squeezing, unsqueezing and permuting

In [11]:
q = torch.randn(1, 3, 1, 5)
print('original:', q.shape)
print('squeezed:', q.squeeze().shape)
u = q.squeeze().unsqueeze(0)
print('unsqueezed:', u.shape)
img = torch.randn(2, 3, 32, 32)
print('NCHW:', img.shape)
print('NHWC:', img.permute(0, 2, 3, 1).shape)

original: torch.Size([1, 3, 1, 5])
squeezed: torch.Size([3, 5])
unsqueezed: torch.Size([1, 3, 5])
NCHW: torch.Size([2, 3, 32, 32])
NHWC: torch.Size([2, 32, 32, 3])


## 27. Selecting data (indexing)

In [12]:
idx = torch.tensor([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print('first row:', idx[0])
print('last col:', idx[:, -1])
print('center:', idx[1, 1])
print('slice:', idx[0:2, 1:3])
print('mask > 45:', idx[idx > 45])

first row: tensor([10, 20, 30])
last col: tensor([30, 60, 90])
center: tensor(50)
slice: tensor([[20, 30],
        [50, 60]])
mask > 45: tensor([50, 60, 70, 80, 90])


## 28. PyTorch and NumPy

In [13]:
arr = np.array([1.0, 2.0, 3.0], dtype=np.float32)
t_from_np = torch.from_numpy(arr)
t = torch.tensor([10.0, 20.0, 30.0])
arr_from_t = t.numpy()
arr[0] = 99.0
t[1] = -5.0
print('torch from numpy:', t_from_np)
print('numpy from torch:', arr_from_t)

torch from numpy: tensor([99.,  2.,  3.])
numpy from torch: [10. -5. 30.]


## 29. Reproducibility

In [14]:
torch.manual_seed(42)
r1 = torch.rand(3)
torch.manual_seed(42)
r2 = torch.rand(3)
print('r1:', r1)
print('r2:', r2)
print('same:', torch.equal(r1, r2))

r1: tensor([0.8823, 0.9150, 0.3829])
r2: tensor([0.8823, 0.9150, 0.3829])
same: True


## 30. Accessing a GPU

In [15]:
print('CUDA available:', torch.cuda.is_available())
print('MPS available:', torch.backends.mps.is_available() if hasattr(torch.backends, 'mps') else False)
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))

CUDA available: False
MPS available: True


## 31. Setting up device agnostic code

In [16]:
def get_device():
    if torch.cuda.is_available():
        return torch.device('cuda')
    if hasattr(torch.backends, 'mps') and torch.backends.mps.is_available():
        return torch.device('mps')
    return torch.device('cpu')

device = get_device()
print('Using device:', device)

x = torch.randn(4, 3).to(device)
model = torch.nn.Linear(3, 2).to(device)
out = model(x)
print('x device:', x.device)
print('model device:', model.weight.device)
print('out shape:', out.shape)

Using device: mps
x device: mps:0
model device: mps:0
out shape: torch.Size([4, 2])


## Practice
- Change shapes and predict outputs before running
- Trigger one matrix shape mismatch to read the error
- Verify NumPy/PyTorch shared memory behavior
- Re-run reproducibility cell and confirm matching random values