In [1]:
# set up
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# SCALAR
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# get scalar back as Python int
scalar.item()

7

In [5]:
# VECTOR
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix[0]

tensor([7, 8])

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
# TENSOR
my_tensor = torch.tensor([[[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]]])
my_tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
my_tensor.ndim

3

In [14]:
my_tensor.shape

torch.Size([1, 3, 3])

In [15]:
# Random Tensors
random_tensor = torch.rand(2, 2, 3, 2)
random_tensor

tensor([[[[0.5792, 0.2247],
          [0.1913, 0.0364],
          [0.9557, 0.7615]],

         [[0.7248, 0.4419],
          [0.9233, 0.2583],
          [0.6143, 0.0734]]],


        [[[0.2283, 0.1076],
          [0.8725, 0.2909],
          [0.4311, 0.6817]],

         [[0.1625, 0.1894],
          [0.8343, 0.9032],
          [0.3749, 0.0977]]]])

In [16]:
# image tensor
random_image_size_tensor = torch.rand(32, 32, 3)    # 32 by 32 pixels with 3 color channels for RGB values

In [17]:
# zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
# range
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_ones = torch.ones_like(one_to_ten)
ten_rand = torch.rand_like(one_to_ten.float())
ten_zeros, ten_ones, ten_rand

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([0.4042, 0.7519, 0.7768, 0.5985, 0.5514, 0.2698, 0.9184, 0.8741, 0.4789,
         0.0194]))

In [22]:
# Tensor Datatypes
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32)
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype

torch.float32

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)